from --platform=$BUILDPLATFORM alpine as build-env
ADD gotify-linux-amd64 ./
ADD gotify-linux-arm64 ./
RUN [ "$(uname -m)" != 'aarch64' ] && cp ./gotify-linux-amd64 /gotify-app || cp ./gotify-linux-arm64 /gotify-app

FROM frolvlad/alpine-glibc:glibc-2.31
RUN apk add --no-cache ca-certificates tzdata curl jq
ENV GOTIFY_SERVER_PORT="80"
WORKDIR /app/
COPY --from=build-env /gotify-app /app/
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s CMD curl --fail http://localhost:$GOTIFY_SERVER_PORT/health || exit 1
EXPOSE 80
ENTRYPOINT ["./gotify-app"]
