FROM frolvlad/alpine-glibc:glibc-2.31
RUN ARCH="$(uname -m)"; if [[ $ARCH == 'aarch64' ]];then;F_EXT=arm64;else;F_EXT=amd64 && \
	apk add --no-cache ca-certificates tzdata curl jq
ENV GOTIFY_SERVER_PORT="80"
WORKDIR /app
ADD ../build/gotify-linux-"$F_EXT" /app/gotify-app
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s CMD curl --fail http://localhost:$GOTIFY_SERVER_PORT/health || exit 1
EXPOSE 80
ENTRYPOINT ["./gotify-app"]
