FROM --platform=$BUILDPLATFORM golang:alpine as build-env

# Install TARGETPLATFORM parser to translate its value to GOOS, GOARCH, and GOARM
COPY --from=tonistiigi/xx:golang / /

# Bring TARGETPLATFORM to the build scope
ARG TARGETPLATFORM

# Build using GOOS, GOARCH, and GOARM
RUN apk add --no-cache ca-certificates tzdata curl git && git clone https://github.com/gotify/server gotify && cd gotify && \
	CGO_ENABLED=0 go build -a -o /gotify-app .


FROM frolvlad/alpine-glibc:glibc-2.31
WORKDIR /app

COPY --from=build-env /gotify-app ./

ADD gotify-app /app/

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s CMD curl --fail http://localhost:$GOTIFY_SERVER_PORT/health || exit 1

ENV GOTIFY_SERVER_PORT="80"
EXPOSE 80
ENTRYPOINT ["./gotify-app"]
